CREATE TABLE [ingestion].[File]
(
	[Id] INT IDENTITY(1, 1) NOT NULL,
	[Name] NVARCHAR(256) NOT NULL,
	[Hash] NVARCHAR(128) NOT NULL,
	[Path] NVARCHAR(1024) NOT NULL,
	[Size] BIGINT NOT NULL,
	[CreatedOnUtc] DATETIMEOFFSET NOT NULL,

	CONSTRAINT [PK_Ingestion_File] PRIMARY KEY ([Id])
)
GO
